name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  validate:
    name: Validate Structure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check website folder
        run: test -d website

      - name: Check index.html
        run: test -f website/index.html

      - name: Check environment
        run: ./scripts/validate_env.sh

  lint:
    name: Lint HTML
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Validate DOCTYPE
        run: grep "<!DOCTYPE html>" website/index.html

  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Package website
        run: |
          mkdir dist
          cp -r website/* dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist